apiVersion: apps/v1
kind: Deployment
metadata:
  name: nec-middleware-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nec-middleware-service
  template:
    metadata:
      labels:
        app: nec-middleware-service
    spec:
      containers:
        - name: nec-middleware
          image: chantihub/nec-middleware-service:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.database.svc.cluster.local:3306/emis?useSSL=false&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: appuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: AppUserPwd

          resources:
            requests:
              cpu: "250m"
              memory: "768Mi"
            limits:
              cpu: "500m"
              memory: "1.5Gi"

          readinessProbe:
            httpGet:
              path: /ams/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /ams/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          startupProbe:
            httpGet:
              path: /ams/actuator/health
              port: 8080
            failureThreshold: 60
            periodSeconds: 10
